#!/bin/sh

# script for multi step fabber for dsc (based on Basil_tester)

# HISTORY


# deal with options
until [ -z $1 ]; do
    case $1 in
	-o) outflag=1 outdir=$2;;
	-i) inflag=1 infile=$2;; #input/data file
	-m) mask=$2;;
	-@) options=$2;; #options file (text)
     esac
    shift
done

# version of MVNtool to use
#mvntool=~/cproject/fabber/mvntool_script
#mvntool=~/cproject/fabber/mvntool
#fabber=fabber
mvntool=mvntool
fabber=~/cproject/fabber/fabber

alloptions="--data-order=singlefile"
vboptions="--allow-bad-voxels"

# set the output directory here if not specified
if [ -z $outflag ]; then
    echo "Ouput being placed in basil subdirectory of input directory"
    outdir=$indir/basil;
fi

# Start by looking for the output directory (and create if need be)
if [ ! -d $outdir ]; then
  echo "Creating output directory"
  mkdir $outdir;
fi

# do basic cbf first
$fabber --data=$infile --mask=$mask --output=$outdir/step1 --method=vb --convergence=trialmode --max-iterations=20 --noise=white $alloptions $vboptions -@ $options

# now add delay
$mvntool --input=$outdir/step1/finalMVN --output=$outdir/temp --mask=$mask --param=3 --new --val=0 --var=0.01
$fabber --data=$infile --mask=$mask --output=$outdir/step2 --method=vb --convergence=trialmode --max-iterations=20 --noise=white --infertau --continue-from-mvn=$outdir/temp.nii.gz $alloptions $vboptions -@ $options

# now add VTM
$mvntool --input=$outdir/step3/finalMVN --output=$outdir/temp --mask=$mask --param=4 --new --val=10 --var=1
$mvntool --input=$outdir/temp --output=$outdir/temp --mask=$mask --param=5 --new --val=0.5 --var=10

$fabber --data=$infile --mask=$mask --output=$outdir/step4 --method=vb --convergence=trialmode --max-iterations=20 --noise=white --inferart --infertau --continue-from-mvn=$outdir/temp --continue-fwd-only $alloptions $vboptions -@ $options





echo "End."