#!/bin/sh

# BASIL_EPOCH: Epochwise Bayesian Arterial SpIn Labeling parameter estimation
#
# Michael Chappell, IBME & FMRIB Image Analysis Group
#
# Copyright (c) 2012 University of Oxford
#
# SHCOPYRIGHT


Usage() {
    echo "Epochwise Bayesian Inference for Arterial Spin Labelling MRI"
    echo "Version: a.1"
    echo ""
    echo "Usage:"
    echo ""
}

# deal with options

if [ -z $1 ]; then
    Usage
    exit 1
fi

basilcmds=""
until [ -z $1 ]; do
    case $1 in
	-o) outflag=1 outdir=$2
	    shift;;
	-i) inflag=1 infile=$2 #input/data file
	    shift;;
	-@) basil_options=$2
	    shift;;
	--elen) elen=$2
	    shift;;
	--eol) eol=$2
	    shift;;
	--eunit) eunit=$2
	    shift;;
	--devel) devel=1;; #implement development version
	*)  basilcmds="$basilcmds $1" #all other command line options are stored ready to be passed to basil
	    ;;
    esac
    shift
done
# set the output directory here if not specified
if [ -z $outflag ]; then
    echo "Ouput being placed in basilep subdirectory of input directory"
    outdir=$indir/basilep;
fi

# Start by looking for the output directory (and create if need be)
count=0
while [ -d $outdir ]; do
    outdir=$outdir"+"
    count=`expr $count + 1`

    if [ $count -gt 20 ]; then
	echo "Error: $outdir too many existing output directories (i.e. shall not add another +)"
	exit
    fi
done
echo "Creating output directory: $outdir"
mkdir $outdir;

if [ ! -z $eunit ]; then
aslfileopts=$aslfileopts"--eunit=$eunit "
fi

# work out number of TIs
ntis=`awk -F "--ti" '{s+=(NF-1)} END {print s}' $basil_options`
echo "Numer of TIs: $ntis"

# break data into epochs
asl_file --data=$infile --ntis=$ntis --ibf=rpt --iaf=diff --epoch=$outdir/aslepoch --elen=$elen --eol=$eol $aslfileopts

# work out how many epochs we have
#nepoch=`ls $outdir/aslepoch* | wc | awk {'print $1'}`
#echo $nepoch

# do basil analysis on each epoch
for e in `ls $outdir/aslepoch*`; do
    basil -i $e -o `imglob $e` -@ $basil_options $basilcmds
done
