#!/bin/sh

# BASIL: Bayesian Arterial SpIn Labeling parameter estimation
#
# Michael Chappell, FMRIB Image Analysis Group
#
# Copyright (c) 2007 University of Oxford
#
# 


# deal with options

if [ -z $1 ]; then
    echo "Bayesian Inference for Arterial Spin Labelling MRI"
    echo "Version: 0.9 (pre-release internal)"
    echo ""
    echo "Usage (optional parameters in {}):"
    echo " -i         : specify input/data file"
    echo " {-o}       : specify output directory"
    echo " -m         : specify brain mask file"
    echo " -@         : specify parameter options file"
    echo " Extended options:"
    echo " --nlls     : Only do least squares analysis"
    echo " --infertau : Add step to infer on bolus length"
    echo " --infert1  : Add step to include uncertainty in T1 values"
    echo " --inferart : Add step to infer on arterial compartment (GRASE only)"
    echo " --inferinveff : Add step to infer on slope in inversion efficiency (GRASE only)"
    echo ""
    break
else

until [ -z $1 ]; do
    case $1 in
	-o) outflag=1 outdir=$2
	    shift;;
	-i) inflag=1 infile=$2 #input/data file
	    shift;;
	-m) mask=$2
	    shift;;
	-@) options=$2 #options file (text)
	    shift;;
	--nlls) nllsonly=1;;
	--inferart) inferart=1;;
	--infert1) infert1=1;;
	--inferinveff) inveff=1;;
	--infertau) infertau=1;;
    esac
    shift
done


# version of software to use
#mvntool=/home/fs0/chappell/cproject/fabber/mvntool_script
mvntool=/home/fs0/chappell/cproject/fabber/mvntool
fabber=/home/fs0/chappell/cproject/fabber/fabber
#mvntool=${FSLDIR}/bin/mvntool
#fabber=${FSLDIR}/bin/fabber


# set the output directory here if not specified
if [ -z $outflag ]; then
    echo "Ouput being placed in basil subdirectory of input directory"
    outdir=$indir/basil;
fi

# Start by looking for the output directory (and create if need be)
if [ ! -d $outdir ]; then
  echo "Creating output directory"
  mkdir $outdir;
fi

allinstruct="--data-order=singlefile"
vbinstruct="--method=vb --convergence=trialmode --max-iterations=20 --noise=white --allow-bad-voxels"

step=1
# STEP 1: NLLS (2 param)
echo "STEP $step: NLLS (2 param: CBF and ^t)"
$fabber --data=$infile --mask=$mask --output=$outdir/step$step  $allinstruct --method=nlls -@ $options
echo "STEP $step: NLLS (2 param: CBF and ^t)" > $outdir/step$step/info.txt

if [ ! -z $nllsonly ]; then
    echo "NLLS completed: stopping here"
    break
else


stepfrom=$step
step=`expr $step + 1`

# STEP 2: VB (2 param)
echo "STEP $step: VB (2 param: CBF and ^t) - init with STEP $stepfrom"
$fabber --data=$infile --mask=$mask --output=$outdir/step$step $allinstruct $vbinstruct --continue-from-mvn=$outdir/step${stepfrom}/finalMVN.nii.gz --continue-fwd-only -@ $options
nparam=2
paramtext="CBF, ^t"
echo "STEP $step: VB (2 param: CBF and ^t) - init with STEP $stepfrom"  > $outdir/step$step/info.txt

stepfrom=$step
step=`expr $step + 1`

if [ ! -z $inveff ]; then
# STEP: VB add inversion efficiency
    nparam=3
    paramtext=$paramtext", inv eff"
    echo "STEP $step: VB ($nparam param: $paramtext) - init with STEP $stepfrom"
   
    addinstruct="--inferinveff"
    $mvntool --input=$outdir/step${stepfrom}/finalMVN --output=$outdir/temp --mask=$mask --param=3 --new --val=0 --var=0.01
    $fabber --data=$infile --mask=$mask --output=$outdir/step$step $allinstruct $vbinstruct $addinstruct --continue-from-mvn=$outdir/temp -@ $options
    echo "STEP $step: VB ($nparam param: $paramtext) - init with STEP $stepfrom" > $outdir/step$step/info.txt

    stepfrom=$step
    step=`expr $step + 1`
fi


tauinf=0  #by default no tau inference
if [ ! -z $infertau ]; then
# STEP: VB add variable bolus length
    nparam=`expr $nparam + 1`
    tauinf=1 #indicate that tau has been included for parameter insertion below
    paramtext=$paramtext", tau"
    echo "STEP $step: VB ($nparam param: $paramtext) - init with STEP $stepfrom"
    
    $mvntool --input=$outdir/step${stepfrom}/finalMVN --output=$outdir/temp --mask=$mask --param=3 --new --val=2 --var=10

    addinstruct=$addinstruct" --infertau"
    $fabber --data=$infile --mask=$mask --output=$outdir/step$step $allinstruct $vbinstruct $addinstruct --continue-from-mvn=$outdir/temp -@ $options
    echo "STEP $step: VB ($nparam param: $paramtext) - init with STEP $stepfrom" > $outdir/step$step/info.txt
    
    stepfrom=$step
    step=`expr $step + 1`
fi


artinf=0 # by default no arterial inference
if [ ! -z $inferart ]; then
# STEP: VB add arterial compartment
    nparam=`expr $nparam + 2`
    artinf=2 #indicate that arterial inference (two parameters) is being carried out for parameter insertion below
    insposn=`expr 2 + $tauinf + 1` #sets position for arterial parameters to be inserted by mvntool
    paramtext=$paramtext", bCBF, b^t"
      
    $mvntool --input=$outdir/step${stepfrom}/finalMVN --output=$outdir/temp --mask=$mask --param=$insposn --new --val=10 --var=1
    $mvntool --input=$outdir/temp --output=$outdir/temp --mask=$mask --param=`expr $insposn + 1` --new --val=0.5 --var=10

    if [ ! -z $infertau ]; then
    # add bolus length for arterial cpt if needed
	nparam=`expr $nparam + 1`
	paramtest=$paramtext", btau"
	$mvntool --input=$outdir/temp --output=$outdir/temp --mask=$mask --param=`expr $insnposn +1` --new --val=2 --var=10
    fi

    echo "STEP $step: VB ($nparam param: $paramtext) - init with STEP $stepfrom"

    addinstruct=$addinstruct" --inferart"
    $fabber --data=$infile --mask=$mask --output=$outdir/step$step $allinstruct $vbinstruct $addinstruct --continue-from-mvn=$outdir/temp -@ $options
    echo "STEP $step: VB ($nparam param: $paramtext) - init with STEP $stepfrom" > $outdir/step$step/info.txt

    stepfrom=$step
    step=`expr $step + 1`
fi



if [ ! -z $infert1 ]; then
# STEP: VB add variable T1
    nparam=`expr $nparam + 2`
    insposn=`expr 2 + $tauinf + $artinf + 1` # sets postion for T1 parameters to be inserved by mvntool
    paramtext=$paramtext", T1, T1b"
    echo "STEP $step: VB ($nparam param: $paramtext) - init with STEP $stepfrom"
   
    $mvntool --input=$outdir/step${stepfrom}/finalMVN --output=$outdir/temp --mask=$mask --param=$insposn --new --val=1.3 --var=0.01 
    $mvntool --input=$outdir/temp --output=$outdir/temp --mask=$mask --param=`expr $insposn + 1` --new --val=1.5 --var=0.01
    
    addinstruct=$addinstruct" --infert1"
    $fabber --data=$infile --mask=$mask --output=$outdir/step$step $allinstruct $vbinstruct $addinstruct --continue-from-mvn=$outdir/temp -@ $options
    echo "STEP $step: VB ($nparam param: $paramtext) - init with STEP $stepfrom" > $outdir/step$step/info.txt
fi
fi
fi

echo "End."
